import static org.junit.Assert.*;

import org.junit.Test;

import com.ict100.junitprojects.Calculator;

public class CalculatorTest {

	@Test
	public void CalulatorTest() {
		assertEquals("error in add()", 3, Calculator.addition(1, 2));
		assertEquals("error in add()", -3, Calculator.addition(-1, -2));
		assertEquals("error in add()", 9, Calculator.addition(9, 0));
	
	}

	public void calculatorTestAddFail() {
		assertEquals("error in add()", 0, Calculator.addition(1, 2));
		
	}
	
	public void calculatorTestSubPass() 
	{
		assertEquals("error in sub()", 1, Calculator.addition(1, 2));
		assertEquals("error in sub()", -1, Calculator.addition(-1, -2));
		assertEquals("error in sub()", 0, Calculator.addition(2, 1));
	}

	public void calculatorTestsubFail() {
		assertEquals("error in add()", 0, Calculator.addition(2, 1));
		
	}
}
