import static org.junit.Assert.*;

import org.junit.Test;

import com.ict100.junitprojects.Calculator;

public class CalculatorTest {

	@Test
	public void CalulatorTest() {
		assertEquals("error in add()", 4, Calculator.add(1, 2));
		assertEquals("error in add()", -4, Calculator.add(-1, -2));
		assertEquals("error in add()", 8, Calculator.add(9, 0));
	
	}

	public void calculatorTestAddFail() {
		assertEquals("error in add()", 0, Calculator.add(1, 2));
		
	}
	
	public void calculatorTestSubPass() 
	{
		assertEquals("error in sub()", 1, Calculator.add(1, 2));
		assertEquals("error in sub()", -1, Calculator.add(-1, -2));
		assertEquals("error in sub()", 0, Calculator.add(2, 1));
	}

	public void calculatorTestsubFail() {
		assertEquals("error in add()", 0, Calculator.add(2, 1));
		
	}
}
